Done
prog-1/functions pull request #4
Opened 2021-11-06 11:26 UTC by Sp0ozy

2021-11-06 12:27 UTC, zayac commented
Well done!

2021-11-07 18:08 UTC, yarcat requested changes

2021-11-07 18:08 UTC, yarcat commented on exercises/01_sort4/sort4.go
> +	} else {
optional: You don't need this `else`

```go
if a <= b {
  return a, b
}
return b, a
```

2021-11-07 18:08 UTC, yarcat commented on exercises/02_sort3/sort3.go
> +	} else {
The same here

2021-11-07 18:08 UTC, yarcat commented on exercises/04_power/power.go
> +	if y == 0 {
You don't need these explicit checks. Consider the following:
```go
res := 1
for ; y > 0; y-- {
  res *= x
}
return res
```

2021-11-07 18:08 UTC, yarcat commented on exercises/04_power/power.go
> +	if y < 0 {
That's great that you've added this check to your main, but it isn't tested by your program. Please test negative `y`

2021-11-07 18:08 UTC, yarcat commented on exercises/04_power/power_test.go
> +		{1, 1, 1},
I would also expect 
* Negative `y`
* Both `x` and `y` being 0

2026-07-12 12:06 UTC, closed without merging